package app

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// statuslineColors maps a provider route to an ANSI SGR attribute for the
// dialect name, so terminals running several dialects side by side can be told
// apart at a glance.
var statuslineColors = map[string]string{
	"codex":    "1;36",
	"claude":   "1;35",
	"gemini":   "1;34",
	"kimi":     "1;33",
	"xai":      "1;31",
	"glm":      "1;32",
	"minimax":  "1;91",
	"deepseek": "1;94",
	"cursor":   "1;95",
	"copilot":  "1;92",
	"mixed":    "1;96",
}

func statuslineScriptPath(name string) (string, error) {
	home, err := homeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, "instances", name, "statusline.sh"), nil
}

// statuslineScriptContent renders the per-dialect statusline script with the
// dialect name baked in. The name is safe to embed verbatim: validName
// restricts it to [a-z0-9_-], which needs no escaping in the shell single
// quotes or the jq string literal.
func statuslineScriptContent(name string, dialect Dialect) string {
	color, ok := statuslineColors[providerForDialect(dialect)]
	if !ok {
		color = "1;36"
	}
	label := fmt.Sprintf(`\u001b[%sm%s\u001b[0m`, color, name)
	return fmt.Sprintf(`#!/bin/sh
# Generated by cc-dialect — statusline for dialect %q.
# Managed by cc-dialect: outdated copies are regenerated on run. To customize,
# point statusLine in claude/settings.json at your own script instead of
# editing this file; to remove the statusline, delete the statusLine key there
# (it will not be re-added).
command -v jq >/dev/null 2>&1 || exit 0
jq -r '"%s · \(.model.display_name)\(if .effort then " · effort:\(.effort.level)" else "" end)\(if .context_window.used_percentage != null then " · ctx \(.context_window.used_percentage | round)%%" else "" end)"'
`, name, label)
}

// seedStatusline writes the per-dialect statusline script and, on first
// seeding, wires it into the instance settings.json. It never overwrites an
// existing statusLine setting, and an already-present script marks the
// instance as seeded once: a user who removed the statusLine key afterwards
// has opted out, so the key is not re-added. Outdated script content is
// regenerated so binary upgrades propagate template improvements.
func seedStatusline(name string, dialect Dialect) error {
	if !validName(name) {
		return operationError(ErrorInvalidInput, "invalid dialect name %q", name)
	}
	scriptPath, err := statuslineScriptPath(name)
	if err != nil {
		return err
	}
	claudeDir, err := claudeConfigDir(name)
	if err != nil {
		return err
	}
	settingsPath := filepath.Join(claudeDir, "settings.json")
	settings := map[string]any{}
	settingsData, readErr := os.ReadFile(settingsPath)
	switch {
	case readErr == nil:
		// A settings file Claude Code cannot have written (malformed JSON) must
		// not be clobbered; leave the instance untouched and let the caller warn.
		if err = json.Unmarshal(settingsData, &settings); err != nil {
			return fmt.Errorf("parse %s: %w", settingsPath, err)
		}
	case errors.Is(readErr, os.ErrNotExist):
	default:
		return readErr
	}
	content := statuslineScriptContent(name, dialect)
	current, scriptErr := os.ReadFile(scriptPath)
	if scriptErr != nil && !errors.Is(scriptErr, os.ErrNotExist) {
		return scriptErr
	}
	seeded := scriptErr == nil
	if !seeded || string(current) != content {
		if err = atomicWriteFile(scriptPath, []byte(content), 0o755); err != nil {
			return err
		}
	}
	if _, exists := settings["statusLine"]; exists || seeded {
		return nil
	}
	// statusLine.command is executed by a shell, and the default config root
	// (~/Library/Application Support/claude-dialects) contains a space — the
	// stored command must be quoted to survive word splitting.
	settings["statusLine"] = map[string]any{"type": "command", "command": shellQuote(scriptPath)}
	merged, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return err
	}
	if writeErr := atomicWriteFile(settingsPath, append(merged, '\n'), 0o600); writeErr != nil {
		// Roll back the script written moments ago on a failed first-time
		// settings write, so the next run retries the full seed instead of
		// reading the leftover script as an opt-out.
		if !atomicWriteCommitted(writeErr) {
			_ = os.Remove(scriptPath)
		}
		return writeErr
	}
	return nil
}

// shellQuote wraps a string in single quotes for safe use as a shell word,
// escaping any embedded single quotes.
func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `'\''`) + "'"
}

// warnStatuslineSeed reports a failed statusline seed without failing the
// surrounding operation — the statusline is cosmetic.
func warnStatuslineSeed(name string, err error) {
	fmt.Fprintf(os.Stderr, "Warning: statusline for %q not seeded: %v\n", name, err)
}
